/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import conexoes.ConexaoSQLLite;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Willian
 */
public class LoadProject extends javax.swing.JFrame {

    /**
     * Creates new form LoadProject
     */
    public LoadProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carregar Projeto");
        setResizable(false);

        jLabel1.setText("Project:");

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //txtPath.setText("F:\\Desenvolvimento\\Projetos\\arqsw_20172_grupo2\\TP5\\TesteArchitecturePattern\\dependencies.txt");
        jFileChooser1.setDialogTitle("Selecione o projeto");
        jFileChooser1.setFileSelectionMode(jFileChooser1.DIRECTORIES_ONLY);
        //FileFilter filter = new FileNameExtensionFilter("Dependencias Texto", "txt","text");
        //jFileChooser1.addChoosableFileFilter(filter);
        //jFileChooser1.setAcceptAllFileFilterUsed(false);
        //jFileChooser1.setMultiSelectionEnabled(true);
        int file = jFileChooser1.showOpenDialog(this);
        if (file == jFileChooser1.APPROVE_OPTION) {
            File f = jFileChooser1.getSelectedFile();
            txtPath.setText(jFileChooser1.getSelectedFile().getAbsolutePath());
            Runtime run = Runtime.getRuntime();
            try {
                //String cmd = "java -jar /home/ubuntu/Documents/javadepextractor.jar " + txtPath.getText();
                String cmd = "java -jar javadepextractor.jar " + txtPath.getText();
                
                System.out.println(cmd);
                run.exec(cmd);

                JOptionPane.showMessageDialog(this, "Projeto carregado com sucesso!");
                Properties props = new Properties();
                FileOutputStream config = new FileOutputStream("config.properties");
                props.setProperty("path", txtPath.getText());
                //propSalvar.setProperty("porta", "alguma coisa ai veio");
                //props.load(config);               
                props.store(config, null);
                System.out.println("teste");
            } catch (IOException ex) {
                Logger.getLogger(LoadProject.class.getName()).log(Level.SEVERE, null, ex);
            }
            ConexaoSQLLite connection = new ConexaoSQLLite();
            String tables = "CREATE TABLE IF NOT EXISTS project (id INTEGER PRIMARY KEY AUTOINCREMENT, origem VARCHAR(255) NOT NULL,tipo VARCHAR(30) NOT NULL,destino VARCHAR(255) NOT NULL)";
            String insert = "INSERT INTO project(origem,tipo,destino) VALUES(?,?,?);";
            String del = "DELETE FROM project";
            if (connection.conectar()) {
                try {
                    Statement stmt = connection.criarStatement();
                    stmt.execute(tables);
                    stmt.execute(del);
                    Scanner ler = new Scanner(System.in);
                    //String nome = "F:\\Desenvolvimento\\Projetos\\arqsw_20182_grupo1\\TP7\\src\\TestTP7\\src\\dependencies.txt";
                    String nome = txtPath.getText() + "\\dependencies.txt";
                    try {
                        FileReader arq = new FileReader(nome);
                        BufferedReader lerArq = new BufferedReader(arq);
                        String linha = lerArq.readLine(); // lê a primeira linha
                        // a variável "linha" recebe o valor "null" quando o processo
                        // de repetição atingir o final do arquivo texto
                        PreparedStatement prepareStatement = connection.preparesStatement(insert);
                        while (linha != null) {
                            System.out.println("Teste");
                            System.out.printf("%s\n", linha);
                            linha = lerArq.readLine(); // lê da segunda até a última linha
                            String[] dados = linha.split(",");
                            prepareStatement.setString(1, dados[0]);
                            prepareStatement.setString(2, dados[1]);
                            prepareStatement.setString(3, dados[2]);
                            prepareStatement.execute();
                        }

                        arq.close();
                    } catch (IOException e) {
                        System.err.printf("Erro na abertura do arquivo: %s.\n",
                                e.getMessage());
                    }
                } catch (Exception e) {

                } finally {

                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
